package ie.daithi.cards.web.model.enums

enum class EventType {
    REPLAY, DEAL, CALL, PASS, CHOOSE_FROM_DUMMY, BUY_CARDS, BUY_CARDS_NOTIFICATION, CARD_PLAYED, LAST_CARD_PLAYED, GAME_OVER, ROUND_COMPLETED, HAND_COMPLETED;
}