server: 
  address: 0.0.0.0
  port: ${PORT}
  error.include-message: always
  ssl.trusted-certificates: /etc/ssl/cert.pem

# MongoDB
spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: cards-110
    redis.repositories.enabled: ${REDIS_REPO_ENABLED:false}
  security:
    oauth2.resourceserver.jwt.issuer-uri: ${AUTH0_CLIENT_ID}
  jackson: 
    default-property-inclusion: non_null
  mvc: 
    pathmatch.matching-strategy: ant_path_matcher

# Security
cors.whitelist: ${CORS_WHITELIST}

auth0:
  audience: ${AUTH0_AUDIENCE}
  secret: ${AUTH0_SECRET}

# Logging
logging:
  level: 
    org.springframework.web: WARN
    ie.daithi: ${LOGGING_LEVEL:INFO}
    # org.springframework.data.mongodb: DEBUG
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ./logs/application.log

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /

#management:
#  endpoints:
#    web:
#      base-path: /actuator
#      exposure:
#        include: 'health'
#  endpoint:
#    health:
#      show-details: always
