name: Publish to Dockerhub

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Read value from Properties-file
        id: read_property
        uses: christian-draeger/read-properties@1.1.0
        with:
          path: '.env'
          properties: 'CARDS_API_VERSION'
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: daithihearn/cards-110-api
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ steps.read_property.outputs.CARDS_API_VERSION }}"
